/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain;


import javax.annotation.Generated;

import com.mjiang.email.jooq.domain.tables.BrokerBuyStockInfo;
import com.mjiang.email.jooq.domain.tables.BrokerBuySummary;
import com.mjiang.email.jooq.domain.tables.DragonTigerStock;
import com.mjiang.email.jooq.domain.tables.PublicHoliday;
import com.mjiang.email.jooq.domain.tables.StockInfoBack;
import com.mjiang.email.jooq.domain.tables.StockInfoFront;
import com.mjiang.email.jooq.domain.tables.StockInfoNo;
import com.mjiang.email.jooq.domain.tables.StockTradeHistoryInfo;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>tushare</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BROKER_BUY_STOCK_INFO_PRIMARY = Indexes0.BROKER_BUY_STOCK_INFO_PRIMARY;
    public static final Index BROKER_BUY_SUMMARY_BROKER_BUY_SUMMARY_UNI_INDEX = Indexes0.BROKER_BUY_SUMMARY_BROKER_BUY_SUMMARY_UNI_INDEX;
    public static final Index BROKER_BUY_SUMMARY_PRIMARY = Indexes0.BROKER_BUY_SUMMARY_PRIMARY;
    public static final Index DRAGON_TIGER_STOCK_PRIMARY = Indexes0.DRAGON_TIGER_STOCK_PRIMARY;
    public static final Index DRAGON_TIGER_STOCK_UNIQUE_INDEX = Indexes0.DRAGON_TIGER_STOCK_UNIQUE_INDEX;
    public static final Index PUBLIC_HOLIDAY_PRIMARY = Indexes0.PUBLIC_HOLIDAY_PRIMARY;
    public static final Index STOCK_INFO_BACK_PRIMARY = Indexes0.STOCK_INFO_BACK_PRIMARY;
    public static final Index STOCK_INFO_BACK_STOCK_INFO_BACK_CODE_DATE_UNIQUE = Indexes0.STOCK_INFO_BACK_STOCK_INFO_BACK_CODE_DATE_UNIQUE;
    public static final Index STOCK_INFO_FRONT_PRIMARY = Indexes0.STOCK_INFO_FRONT_PRIMARY;
    public static final Index STOCK_INFO_FRONT_STOCK_INFO_FRONT_CODE_DATE_UNIQUE = Indexes0.STOCK_INFO_FRONT_STOCK_INFO_FRONT_CODE_DATE_UNIQUE;
    public static final Index STOCK_INFO_NO_PRIMARY = Indexes0.STOCK_INFO_NO_PRIMARY;
    public static final Index STOCK_INFO_NO_STOCK_INFO_NO_CODE_DATE_UNIQUE = Indexes0.STOCK_INFO_NO_STOCK_INFO_NO_CODE_DATE_UNIQUE;
    public static final Index STOCK_TRADE_HISTORY_INFO_PRIMARY = Indexes0.STOCK_TRADE_HISTORY_INFO_PRIMARY;
    public static final Index STOCK_TRADE_HISTORY_INFO_STOCK_TRADE_HISTORY_UNI_INDEX = Indexes0.STOCK_TRADE_HISTORY_INFO_STOCK_TRADE_HISTORY_UNI_INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BROKER_BUY_STOCK_INFO_PRIMARY = Internal.createIndex("PRIMARY", BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO, new OrderField[] { BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO.ID }, true);
        public static Index BROKER_BUY_SUMMARY_BROKER_BUY_SUMMARY_UNI_INDEX = Internal.createIndex("broker_buy_summary_uni_index", BrokerBuySummary.BROKER_BUY_SUMMARY, new OrderField[] { BrokerBuySummary.BROKER_BUY_SUMMARY.BROKER_CODE, BrokerBuySummary.BROKER_BUY_SUMMARY.TS_DATE }, true);
        public static Index BROKER_BUY_SUMMARY_PRIMARY = Internal.createIndex("PRIMARY", BrokerBuySummary.BROKER_BUY_SUMMARY, new OrderField[] { BrokerBuySummary.BROKER_BUY_SUMMARY.ID }, true);
        public static Index DRAGON_TIGER_STOCK_PRIMARY = Internal.createIndex("PRIMARY", DragonTigerStock.DRAGON_TIGER_STOCK, new OrderField[] { DragonTigerStock.DRAGON_TIGER_STOCK.ID }, true);
        public static Index DRAGON_TIGER_STOCK_UNIQUE_INDEX = Internal.createIndex("unique_index", DragonTigerStock.DRAGON_TIGER_STOCK, new OrderField[] { DragonTigerStock.DRAGON_TIGER_STOCK.CODE, DragonTigerStock.DRAGON_TIGER_STOCK.TS_DATE, DragonTigerStock.DRAGON_TIGER_STOCK.BROKER, DragonTigerStock.DRAGON_TIGER_STOCK.REASON }, true);
        public static Index PUBLIC_HOLIDAY_PRIMARY = Internal.createIndex("PRIMARY", PublicHoliday.PUBLIC_HOLIDAY, new OrderField[] { PublicHoliday.PUBLIC_HOLIDAY.ID }, true);
        public static Index STOCK_INFO_BACK_PRIMARY = Internal.createIndex("PRIMARY", StockInfoBack.STOCK_INFO_BACK, new OrderField[] { StockInfoBack.STOCK_INFO_BACK.ID }, true);
        public static Index STOCK_INFO_BACK_STOCK_INFO_BACK_CODE_DATE_UNIQUE = Internal.createIndex("stock_info_back_CODE_DATE_UNIQUE", StockInfoBack.STOCK_INFO_BACK, new OrderField[] { StockInfoBack.STOCK_INFO_BACK.STOCK_CODE, StockInfoBack.STOCK_INFO_BACK.TS_DATE }, true);
        public static Index STOCK_INFO_FRONT_PRIMARY = Internal.createIndex("PRIMARY", StockInfoFront.STOCK_INFO_FRONT, new OrderField[] { StockInfoFront.STOCK_INFO_FRONT.ID }, true);
        public static Index STOCK_INFO_FRONT_STOCK_INFO_FRONT_CODE_DATE_UNIQUE = Internal.createIndex("stock_info_front_CODE_DATE_UNIQUE", StockInfoFront.STOCK_INFO_FRONT, new OrderField[] { StockInfoFront.STOCK_INFO_FRONT.STOCK_CODE, StockInfoFront.STOCK_INFO_FRONT.TS_DATE }, true);
        public static Index STOCK_INFO_NO_PRIMARY = Internal.createIndex("PRIMARY", StockInfoNo.STOCK_INFO_NO, new OrderField[] { StockInfoNo.STOCK_INFO_NO.ID }, true);
        public static Index STOCK_INFO_NO_STOCK_INFO_NO_CODE_DATE_UNIQUE = Internal.createIndex("stock_info_no_CODE_DATE_UNIQUE", StockInfoNo.STOCK_INFO_NO, new OrderField[] { StockInfoNo.STOCK_INFO_NO.STOCK_CODE, StockInfoNo.STOCK_INFO_NO.TS_DATE }, true);
        public static Index STOCK_TRADE_HISTORY_INFO_PRIMARY = Internal.createIndex("PRIMARY", StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO, new OrderField[] { StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.ID }, true);
        public static Index STOCK_TRADE_HISTORY_INFO_STOCK_TRADE_HISTORY_UNI_INDEX = Internal.createIndex("stock_trade_history_uni_index", StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO, new OrderField[] { StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.STOCK_CODE, StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.TS_DATE }, true);
    }
}
