/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain;


import com.mjiang.email.jooq.domain.tables.BrokerBuyStockInfo;
import com.mjiang.email.jooq.domain.tables.BrokerBuySummary;
import com.mjiang.email.jooq.domain.tables.DragonTigerStock;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>tushare</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BROKER_BUY_STOCK_INFO_PRIMARY = Indexes0.BROKER_BUY_STOCK_INFO_PRIMARY;
    public static final Index BROKER_BUY_SUMMARY_PRIMARY = Indexes0.BROKER_BUY_SUMMARY_PRIMARY;
    public static final Index DRAGON_TIGER_STOCK_PRIMARY = Indexes0.DRAGON_TIGER_STOCK_PRIMARY;
    public static final Index DRAGON_TIGER_STOCK_UNIQUE_INDEX = Indexes0.DRAGON_TIGER_STOCK_UNIQUE_INDEX;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BROKER_BUY_STOCK_INFO_PRIMARY = Internal.createIndex("PRIMARY", BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO, new OrderField[] { BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO.ID }, true);
        public static Index BROKER_BUY_SUMMARY_PRIMARY = Internal.createIndex("PRIMARY", BrokerBuySummary.BROKER_BUY_SUMMARY, new OrderField[] { BrokerBuySummary.BROKER_BUY_SUMMARY.ID }, true);
        public static Index DRAGON_TIGER_STOCK_PRIMARY = Internal.createIndex("PRIMARY", DragonTigerStock.DRAGON_TIGER_STOCK, new OrderField[] { DragonTigerStock.DRAGON_TIGER_STOCK.ID }, true);
        public static Index DRAGON_TIGER_STOCK_UNIQUE_INDEX = Internal.createIndex("unique_index", DragonTigerStock.DRAGON_TIGER_STOCK, new OrderField[] { DragonTigerStock.DRAGON_TIGER_STOCK.CODE, DragonTigerStock.DRAGON_TIGER_STOCK.TS_DATE, DragonTigerStock.DRAGON_TIGER_STOCK.BROKER, DragonTigerStock.DRAGON_TIGER_STOCK.REASON }, true);
    }
}
