/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain;


import com.mjiang.email.jooq.domain.tables.BrokerBuyStockInfo;
import com.mjiang.email.jooq.domain.tables.BrokerBuySummary;
import com.mjiang.email.jooq.domain.tables.DragonTigerStock;
import com.mjiang.email.jooq.domain.tables.PublicHoliday;
import com.mjiang.email.jooq.domain.tables.StockTradeHistoryInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tushare
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tushare.broker_buy_stock_info</code>.
     */
    public static final BrokerBuyStockInfo BROKER_BUY_STOCK_INFO = com.mjiang.email.jooq.domain.tables.BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO;

    /**
     * The table <code>tushare.broker_buy_summary</code>.
     */
    public static final BrokerBuySummary BROKER_BUY_SUMMARY = com.mjiang.email.jooq.domain.tables.BrokerBuySummary.BROKER_BUY_SUMMARY;

    /**
     * The table <code>tushare.dragon_tiger_stock</code>.
     */
    public static final DragonTigerStock DRAGON_TIGER_STOCK = com.mjiang.email.jooq.domain.tables.DragonTigerStock.DRAGON_TIGER_STOCK;

    /**
     * The table <code>tushare.public_holiday</code>.
     */
    public static final PublicHoliday PUBLIC_HOLIDAY = com.mjiang.email.jooq.domain.tables.PublicHoliday.PUBLIC_HOLIDAY;

    /**
     * The table <code>tushare.stock_trade_history_info</code>.
     */
    public static final StockTradeHistoryInfo STOCK_TRADE_HISTORY_INFO = com.mjiang.email.jooq.domain.tables.StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO;
}
