/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain;


import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.mjiang.email.jooq.domain.tables.BrokerBuyStockInfo;
import com.mjiang.email.jooq.domain.tables.BrokerBuySummary;
import com.mjiang.email.jooq.domain.tables.DragonTigerStock;
import com.mjiang.email.jooq.domain.tables.PublicHoliday;
import com.mjiang.email.jooq.domain.tables.StockInfoBack;
import com.mjiang.email.jooq.domain.tables.StockInfoFront;
import com.mjiang.email.jooq.domain.tables.StockInfoNo;
import com.mjiang.email.jooq.domain.tables.StockTradeHistoryInfo;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tushare extends SchemaImpl {

    private static final long serialVersionUID = -735111950;

    /**
     * The reference instance of <code>tushare</code>
     */
    public static final Tushare TUSHARE = new Tushare();

    /**
     * The table <code>tushare.broker_buy_stock_info</code>.
     */
    public final BrokerBuyStockInfo BROKER_BUY_STOCK_INFO = BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO;

    /**
     * The table <code>tushare.broker_buy_summary</code>.
     */
    public final BrokerBuySummary BROKER_BUY_SUMMARY = BrokerBuySummary.BROKER_BUY_SUMMARY;

    /**
     * The table <code>tushare.dragon_tiger_stock</code>.
     */
    public final DragonTigerStock DRAGON_TIGER_STOCK = DragonTigerStock.DRAGON_TIGER_STOCK;

    /**
     * The table <code>tushare.public_holiday</code>.
     */
    public final PublicHoliday PUBLIC_HOLIDAY = PublicHoliday.PUBLIC_HOLIDAY;

    /**
     * The table <code>tushare.stock_info_back</code>.
     */
    public final StockInfoBack STOCK_INFO_BACK = StockInfoBack.STOCK_INFO_BACK;

    /**
     * The table <code>tushare.stock_info_front</code>.
     */
    public final StockInfoFront STOCK_INFO_FRONT = StockInfoFront.STOCK_INFO_FRONT;

    /**
     * The table <code>tushare.stock_info_no</code>.
     */
    public final StockInfoNo STOCK_INFO_NO = StockInfoNo.STOCK_INFO_NO;

    /**
     * The table <code>tushare.stock_trade_history_info</code>.
     */
    public final StockTradeHistoryInfo STOCK_TRADE_HISTORY_INFO = StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO;

    /**
     * No further instances allowed
     */
    private Tushare() {
        super("tushare", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO,
            BrokerBuySummary.BROKER_BUY_SUMMARY,
            DragonTigerStock.DRAGON_TIGER_STOCK,
            PublicHoliday.PUBLIC_HOLIDAY,
            StockInfoBack.STOCK_INFO_BACK,
            StockInfoFront.STOCK_INFO_FRONT,
            StockInfoNo.STOCK_INFO_NO,
            StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO);
    }
}
