/*
 * This file is generated by jOOQ.
*/
package domain.tables.records;


import domain.tables.DragonTigerStock;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DragonTigerStockRecord extends UpdatableRecordImpl<DragonTigerStockRecord> implements Record19<Long, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, BigDecimal, Date, String, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1613117786;

    /**
     * Setter for <code>tushare.dragon_tiger_stock.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.pchange</code>.
     */
    public void setPchange(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.pchange</code>.
     */
    public BigDecimal getPchange() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.amount</code>.
     */
    public void setAmount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.amount</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.buy</code>.
     */
    public void setBuy(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.buy</code>.
     */
    public BigDecimal getBuy() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.sell</code>.
     */
    public void setSell(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.sell</code>.
     */
    public BigDecimal getSell() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.reason</code>.
     */
    public void setReason(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.reason</code>.
     */
    public String getReason() {
        return (String) get(7);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.bratio</code>.
     */
    public void setBratio(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.bratio</code>.
     */
    public BigDecimal getBratio() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.sratio</code>.
     */
    public void setSratio(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.sratio</code>.
     */
    public BigDecimal getSratio() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.ts_date</code>.
     */
    public void setTsDate(Date value) {
        set(10, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.ts_date</code>.
     */
    public Date getTsDate() {
        return (Date) get(10);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.broker</code>.
     */
    public void setBroker(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.broker</code>.
     */
    public String getBroker() {
        return (String) get(11);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.count</code>.
     */
    public void setCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.count</code>.
     */
    public Integer getCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.probability</code>.
     */
    public void setProbability(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.probability</code>.
     */
    public BigDecimal getProbability() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.broker_buy</code>.
     */
    public void setBrokerBuy(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.broker_buy</code>.
     */
    public BigDecimal getBrokerBuy() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.broker_buy_prop</code>.
     */
    public void setBrokerBuyProp(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.broker_buy_prop</code>.
     */
    public BigDecimal getBrokerBuyProp() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.broker_sell</code>.
     */
    public void setBrokerSell(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.broker_sell</code>.
     */
    public BigDecimal getBrokerSell() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.broker_sell_prop</code>.
     */
    public void setBrokerSellProp(BigDecimal value) {
        set(17, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.broker_sell_prop</code>.
     */
    public BigDecimal getBrokerSellProp() {
        return (BigDecimal) get(17);
    }

    /**
     * Setter for <code>tushare.dragon_tiger_stock.net</code>.
     */
    public void setNet(BigDecimal value) {
        set(18, value);
    }

    /**
     * Getter for <code>tushare.dragon_tiger_stock.net</code>.
     */
    public BigDecimal getNet() {
        return (BigDecimal) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Long, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, BigDecimal, Date, String, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Long, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, String, BigDecimal, BigDecimal, Date, String, Integer, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.PCHANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BUY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.SELL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.REASON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BRATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.SRATIO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field11() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.TS_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BROKER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field14() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.PROBABILITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BROKER_BUY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field16() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BROKER_BUY_PROP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field17() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BROKER_SELL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field18() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.BROKER_SELL_PROP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field19() {
        return DragonTigerStock.DRAGON_TIGER_STOCK.NET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getPchange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getBuy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getSell();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getBratio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getSratio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component11() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getBroker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component14() {
        return getProbability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component15() {
        return getBrokerBuy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component16() {
        return getBrokerBuyProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component17() {
        return getBrokerSell();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component18() {
        return getBrokerSellProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component19() {
        return getNet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPchange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getBuy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getSell();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getReason();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getBratio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getSratio();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value11() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getBroker();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value14() {
        return getProbability();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getBrokerBuy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value16() {
        return getBrokerBuyProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value17() {
        return getBrokerSell();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value18() {
        return getBrokerSellProp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value19() {
        return getNet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value4(BigDecimal value) {
        setPchange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value5(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value6(BigDecimal value) {
        setBuy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value7(BigDecimal value) {
        setSell(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value8(String value) {
        setReason(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value9(BigDecimal value) {
        setBratio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value10(BigDecimal value) {
        setSratio(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value11(Date value) {
        setTsDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value12(String value) {
        setBroker(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value13(Integer value) {
        setCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value14(BigDecimal value) {
        setProbability(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value15(BigDecimal value) {
        setBrokerBuy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value16(BigDecimal value) {
        setBrokerBuyProp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value17(BigDecimal value) {
        setBrokerSell(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value18(BigDecimal value) {
        setBrokerSellProp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord value19(BigDecimal value) {
        setNet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DragonTigerStockRecord values(Long value1, String value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, String value8, BigDecimal value9, BigDecimal value10, Date value11, String value12, Integer value13, BigDecimal value14, BigDecimal value15, BigDecimal value16, BigDecimal value17, BigDecimal value18, BigDecimal value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DragonTigerStockRecord
     */
    public DragonTigerStockRecord() {
        super(DragonTigerStock.DRAGON_TIGER_STOCK);
    }

    /**
     * Create a detached, initialised DragonTigerStockRecord
     */
    public DragonTigerStockRecord(Long id, String code, String name, BigDecimal pchange, BigDecimal amount, BigDecimal buy, BigDecimal sell, String reason, BigDecimal bratio, BigDecimal sratio, Date tsDate, String broker, Integer count, BigDecimal probability, BigDecimal brokerBuy, BigDecimal brokerBuyProp, BigDecimal brokerSell, BigDecimal brokerSellProp, BigDecimal net) {
        super(DragonTigerStock.DRAGON_TIGER_STOCK);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, pchange);
        set(4, amount);
        set(5, buy);
        set(6, sell);
        set(7, reason);
        set(8, bratio);
        set(9, sratio);
        set(10, tsDate);
        set(11, broker);
        set(12, count);
        set(13, probability);
        set(14, brokerBuy);
        set(15, brokerBuyProp);
        set(16, brokerSell);
        set(17, brokerSellProp);
        set(18, net);
    }
}
