/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables;


import com.mjiang.email.jooq.domain.Indexes;
import com.mjiang.email.jooq.domain.Keys;
import com.mjiang.email.jooq.domain.Tushare;
import com.mjiang.email.jooq.domain.tables.records.SmartWatchRefRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmartWatchRef extends TableImpl<SmartWatchRefRecord> {

    private static final long serialVersionUID = 1862781418;

    /**
     * The reference instance of <code>tushare.smart_watch_ref</code>
     */
    public static final SmartWatchRef SMART_WATCH_REF = new SmartWatchRef();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SmartWatchRefRecord> getRecordType() {
        return SmartWatchRefRecord.class;
    }

    /**
     * The column <code>tushare.smart_watch_ref.id</code>.
     */
    public final TableField<SmartWatchRefRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>tushare.smart_watch_ref.code</code>.
     */
    public final TableField<SmartWatchRefRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>tushare.smart_watch_ref.name</code>.
     */
    public final TableField<SmartWatchRefRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>tushare.smart_watch_ref.color</code>.
     */
    public final TableField<SmartWatchRefRecord, String> COLOR = createField("color", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>tushare.smart_watch_ref.direction</code>.
     */
    public final TableField<SmartWatchRefRecord, String> DIRECTION = createField("direction", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>tushare.smart_watch_ref.pair</code>.
     */
    public final TableField<SmartWatchRefRecord, String> PAIR = createField("pair", org.jooq.impl.SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>tushare.smart_watch_ref.type</code>.
     */
    public final TableField<SmartWatchRefRecord, String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR(50), this, "");

    /**
     * Create a <code>tushare.smart_watch_ref</code> table reference
     */
    public SmartWatchRef() {
        this(DSL.name("smart_watch_ref"), null);
    }

    /**
     * Create an aliased <code>tushare.smart_watch_ref</code> table reference
     */
    public SmartWatchRef(String alias) {
        this(DSL.name(alias), SMART_WATCH_REF);
    }

    /**
     * Create an aliased <code>tushare.smart_watch_ref</code> table reference
     */
    public SmartWatchRef(Name alias) {
        this(alias, SMART_WATCH_REF);
    }

    private SmartWatchRef(Name alias, Table<SmartWatchRefRecord> aliased) {
        this(alias, aliased, null);
    }

    private SmartWatchRef(Name alias, Table<SmartWatchRefRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tushare.TUSHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SMART_WATCH_REF_PRIMARY, Indexes.SMART_WATCH_REF_SMART_WATCH_REF_CODE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SmartWatchRefRecord, Long> getIdentity() {
        return Keys.IDENTITY_SMART_WATCH_REF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SmartWatchRefRecord> getPrimaryKey() {
        return Keys.KEY_SMART_WATCH_REF_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SmartWatchRefRecord>> getKeys() {
        return Arrays.<UniqueKey<SmartWatchRefRecord>>asList(Keys.KEY_SMART_WATCH_REF_PRIMARY, Keys.KEY_SMART_WATCH_REF_SMART_WATCH_REF_CODE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRef as(String alias) {
        return new SmartWatchRef(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRef as(Name alias) {
        return new SmartWatchRef(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public SmartWatchRef rename(String name) {
        return new SmartWatchRef(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SmartWatchRef rename(Name name) {
        return new SmartWatchRef(name, null);
    }
}
