/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables;


import com.mjiang.email.jooq.domain.Indexes;
import com.mjiang.email.jooq.domain.Keys;
import com.mjiang.email.jooq.domain.Tushare;
import com.mjiang.email.jooq.domain.tables.records.StockInfoNoRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockInfoNo extends TableImpl<StockInfoNoRecord> {

    private static final long serialVersionUID = -1695523242;

    /**
     * The reference instance of <code>tushare.stock_info_no</code>
     */
    public static final StockInfoNo STOCK_INFO_NO = new StockInfoNo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockInfoNoRecord> getRecordType() {
        return StockInfoNoRecord.class;
    }

    /**
     * The column <code>tushare.stock_info_no.id</code>.
     */
    public final TableField<StockInfoNoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>tushare.stock_info_no.stock_code</code>.
     */
    public final TableField<StockInfoNoRecord, String> STOCK_CODE = createField("stock_code", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>tushare.stock_info_no.ts_date</code>.
     */
    public final TableField<StockInfoNoRecord, Date> TS_DATE = createField("ts_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>tushare.stock_info_no.open</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> OPEN = createField("open", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.high</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> HIGH = createField("high", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.low</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> LOW = createField("low", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.close</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> CLOSE = createField("close", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.volume</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> VOLUME = createField("volume", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.amount</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ccl</code>.
     */
    public final TableField<StockInfoNoRecord, String> CCL = createField("ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_no.preClose</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> PRECLOSE = createField("preClose", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.netChangeRatio</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> NETCHANGERATIO = createField("netChangeRatio", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma5_volume</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MA5_VOLUME = createField("ma5_volume", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma5_avgPrice</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MA5_AVGPRICE = createField("ma5_avgPrice", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma5_ccl</code>.
     */
    public final TableField<StockInfoNoRecord, String> MA5_CCL = createField("ma5_ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma10_volume</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MA10_VOLUME = createField("ma10_volume", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma10_avgPrice</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MA10_AVGPRICE = createField("ma10_avgPrice", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma10_ccl</code>.
     */
    public final TableField<StockInfoNoRecord, String> MA10_CCL = createField("ma10_ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma20_volume</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MA20_VOLUME = createField("ma20_volume", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma20_avgPrice</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MA20_AVGPRICE = createField("ma20_avgPrice", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.ma20_ccl</code>.
     */
    public final TableField<StockInfoNoRecord, String> MA20_CCL = createField("ma20_ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_no.macd_diff</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MACD_DIFF = createField("macd_diff", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.macd_dea</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MACD_DEA = createField("macd_dea", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.macd</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> MACD = createField("macd", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.kdj_k</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> KDJ_K = createField("kdj_k", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.kdj_d</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> KDJ_D = createField("kdj_d", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.kdj_j</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> KDJ_J = createField("kdj_j", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.rsi1</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> RSI1 = createField("rsi1", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.rsi2</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> RSI2 = createField("rsi2", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * The column <code>tushare.stock_info_no.rsi3</code>.
     */
    public final TableField<StockInfoNoRecord, BigDecimal> RSI3 = createField("rsi3", org.jooq.impl.SQLDataType.DECIMAL(30, 12), this, "");

    /**
     * Create a <code>tushare.stock_info_no</code> table reference
     */
    public StockInfoNo() {
        this(DSL.name("stock_info_no"), null);
    }

    /**
     * Create an aliased <code>tushare.stock_info_no</code> table reference
     */
    public StockInfoNo(String alias) {
        this(DSL.name(alias), STOCK_INFO_NO);
    }

    /**
     * Create an aliased <code>tushare.stock_info_no</code> table reference
     */
    public StockInfoNo(Name alias) {
        this(alias, STOCK_INFO_NO);
    }

    private StockInfoNo(Name alias, Table<StockInfoNoRecord> aliased) {
        this(alias, aliased, null);
    }

    private StockInfoNo(Name alias, Table<StockInfoNoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tushare.TUSHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STOCK_INFO_NO_PRIMARY, Indexes.STOCK_INFO_NO_STOCK_INFO_NO_CODE_DATE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StockInfoNoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STOCK_INFO_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StockInfoNoRecord> getPrimaryKey() {
        return Keys.KEY_STOCK_INFO_NO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StockInfoNoRecord>> getKeys() {
        return Arrays.<UniqueKey<StockInfoNoRecord>>asList(Keys.KEY_STOCK_INFO_NO_PRIMARY, Keys.KEY_STOCK_INFO_NO_STOCK_INFO_NO_CODE_DATE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockInfoNo as(String alias) {
        return new StockInfoNo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockInfoNo as(Name alias) {
        return new StockInfoNo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StockInfoNo rename(String name) {
        return new StockInfoNo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StockInfoNo rename(Name name) {
        return new StockInfoNo(name, null);
    }
}
