/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables;


import javax.annotation.Generated;
import java.math.BigDecimal;
import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import com.mjiang.email.jooq.domain.Indexes;
import com.mjiang.email.jooq.domain.Keys;
import com.mjiang.email.jooq.domain.Tushare;
import com.mjiang.email.jooq.domain.tables.records.StockInfoFrontRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockInfoFront extends TableImpl<StockInfoFrontRecord> {

    private static final long serialVersionUID = -435763416;

    /**
     * The reference instance of <code>tushare.stock_info_front</code>
     */
    public static final StockInfoFront STOCK_INFO_FRONT = new StockInfoFront();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StockInfoFrontRecord> getRecordType() {
        return StockInfoFrontRecord.class;
    }

    /**
     * The column <code>tushare.stock_info_front.id</code>.
     */
    public final TableField<StockInfoFrontRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>tushare.stock_info_front.stock_code</code>.
     */
    public final TableField<StockInfoFrontRecord, String> STOCK_CODE = createField("stock_code", org.jooq.impl.SQLDataType.VARCHAR(45).nullable(false), this, "");

    /**
     * The column <code>tushare.stock_info_front.ts_date</code>.
     */
    public final TableField<StockInfoFrontRecord, Date> TS_DATE = createField("ts_date", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>tushare.stock_info_front.open</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> OPEN = createField("open", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.high</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> HIGH = createField("high", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.low</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> LOW = createField("low", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.close</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> CLOSE = createField("close", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.volume</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> VOLUME = createField("volume", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.amount</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> AMOUNT = createField("amount", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ccl</code>.
     */
    public final TableField<StockInfoFrontRecord, String> CCL = createField("ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_front.preClose</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> PRECLOSE = createField("preClose", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.netChangeRatio</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> NETCHANGERATIO = createField("netChangeRatio", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma5_volume</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MA5_VOLUME = createField("ma5_volume", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma5_avgPrice</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MA5_AVGPRICE = createField("ma5_avgPrice", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma5_ccl</code>.
     */
    public final TableField<StockInfoFrontRecord, String> MA5_CCL = createField("ma5_ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma10_volume</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MA10_VOLUME = createField("ma10_volume", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma10_avgPrice</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MA10_AVGPRICE = createField("ma10_avgPrice", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma10_ccl</code>.
     */
    public final TableField<StockInfoFrontRecord, String> MA10_CCL = createField("ma10_ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma20_volume</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MA20_VOLUME = createField("ma20_volume", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma20_avgPrice</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MA20_AVGPRICE = createField("ma20_avgPrice", org.jooq.impl.SQLDataType.DECIMAL(15, 2), this, "");

    /**
     * The column <code>tushare.stock_info_front.ma20_ccl</code>.
     */
    public final TableField<StockInfoFrontRecord, String> MA20_CCL = createField("ma20_ccl", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>tushare.stock_info_front.macd_diff</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MACD_DIFF = createField("macd_diff", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.macd_dea</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MACD_DEA = createField("macd_dea", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.macd</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> MACD = createField("macd", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.kdj_k</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> KDJ_K = createField("kdj_k", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.kdj_d</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> KDJ_D = createField("kdj_d", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.kdj_j</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> KDJ_J = createField("kdj_j", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.rsi1</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> RSI1 = createField("rsi1", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.rsi2</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> RSI2 = createField("rsi2", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * The column <code>tushare.stock_info_front.rsi3</code>.
     */
    public final TableField<StockInfoFrontRecord, BigDecimal> RSI3 = createField("rsi3", org.jooq.impl.SQLDataType.DECIMAL(15, 6), this, "");

    /**
     * Create a <code>tushare.stock_info_front</code> table reference
     */
    public StockInfoFront() {
        this(DSL.name("stock_info_front"), null);
    }

    /**
     * Create an aliased <code>tushare.stock_info_front</code> table reference
     */
    public StockInfoFront(String alias) {
        this(DSL.name(alias), STOCK_INFO_FRONT);
    }

    /**
     * Create an aliased <code>tushare.stock_info_front</code> table reference
     */
    public StockInfoFront(Name alias) {
        this(alias, STOCK_INFO_FRONT);
    }

    private StockInfoFront(Name alias, Table<StockInfoFrontRecord> aliased) {
        this(alias, aliased, null);
    }

    private StockInfoFront(Name alias, Table<StockInfoFrontRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Tushare.TUSHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STOCK_INFO_FRONT_PRIMARY, Indexes.STOCK_INFO_FRONT_STOCK_INFO_FRONT_CODE_DATE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StockInfoFrontRecord, Integer> getIdentity() {
        return Keys.IDENTITY_STOCK_INFO_FRONT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StockInfoFrontRecord> getPrimaryKey() {
        return Keys.KEY_STOCK_INFO_FRONT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StockInfoFrontRecord>> getKeys() {
        return Arrays.<UniqueKey<StockInfoFrontRecord>>asList(Keys.KEY_STOCK_INFO_FRONT_PRIMARY, Keys.KEY_STOCK_INFO_FRONT_STOCK_INFO_FRONT_CODE_DATE_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockInfoFront as(String alias) {
        return new StockInfoFront(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockInfoFront as(Name alias) {
        return new StockInfoFront(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public StockInfoFront rename(String name) {
        return new StockInfoFront(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public StockInfoFront rename(Name name) {
        return new StockInfoFront(name, null);
    }
}
