/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables.records;


import com.mjiang.email.jooq.domain.tables.BrokerBuySummary;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BrokerBuySummaryRecord extends UpdatableRecordImpl<BrokerBuySummaryRecord> implements Record9<Long, String, String, BigDecimal, BigDecimal, BigDecimal, Long, Long, Date> {

    private static final long serialVersionUID = -1178202609;

    /**
     * Setter for <code>tushare.broker_buy_summary.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.broker_code</code>.
     */
    public void setBrokerCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.broker_code</code>.
     */
    public String getBrokerCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.broker_name</code>.
     */
    public void setBrokerName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.broker_name</code>.
     */
    public String getBrokerName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.s_money</code>.
     */
    public void setSMoney(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.s_money</code>.
     */
    public BigDecimal getSMoney() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.b_money</code>.
     */
    public void setBMoney(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.b_money</code>.
     */
    public BigDecimal getBMoney() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.jm_money</code>.
     */
    public void setJmMoney(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.jm_money</code>.
     */
    public BigDecimal getJmMoney() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.b_count</code>.
     */
    public void setBCount(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.b_count</code>.
     */
    public Long getBCount() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.s_Count</code>.
     */
    public void setSCount(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.s_Count</code>.
     */
    public Long getSCount() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>tushare.broker_buy_summary.ts_date</code>.
     */
    public void setTsDate(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>tushare.broker_buy_summary.ts_date</code>.
     */
    public Date getTsDate() {
        return (Date) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, BigDecimal, BigDecimal, BigDecimal, Long, Long, Date> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, BigDecimal, BigDecimal, BigDecimal, Long, Long, Date> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.BROKER_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.BROKER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.S_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.B_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.JM_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.B_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.S_COUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return BrokerBuySummary.BROKER_BUY_SUMMARY.TS_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getBrokerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getBrokerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getSMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getBMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getJmMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getBCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getSCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component9() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getBrokerCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getBrokerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getSMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getBMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getJmMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getBCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getSCount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value2(String value) {
        setBrokerCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value3(String value) {
        setBrokerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value4(BigDecimal value) {
        setSMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value5(BigDecimal value) {
        setBMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value6(BigDecimal value) {
        setJmMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value7(Long value) {
        setBCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value8(Long value) {
        setSCount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord value9(Date value) {
        setTsDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BrokerBuySummaryRecord values(Long value1, String value2, String value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, Long value7, Long value8, Date value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BrokerBuySummaryRecord
     */
    public BrokerBuySummaryRecord() {
        super(BrokerBuySummary.BROKER_BUY_SUMMARY);
    }

    /**
     * Create a detached, initialised BrokerBuySummaryRecord
     */
    public BrokerBuySummaryRecord(Long id, String brokerCode, String brokerName, BigDecimal sMoney, BigDecimal bMoney, BigDecimal jmMoney, Long bCount, Long sCount, Date tsDate) {
        super(BrokerBuySummary.BROKER_BUY_SUMMARY);

        set(0, id);
        set(1, brokerCode);
        set(2, brokerName);
        set(3, sMoney);
        set(4, bMoney);
        set(5, jmMoney);
        set(6, bCount);
        set(7, sCount);
        set(8, tsDate);
    }
}
