/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables.records;


import com.mjiang.email.jooq.domain.tables.PublicHoliday;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PublicHolidayRecord extends UpdatableRecordImpl<PublicHolidayRecord> implements Record6<Long, Date, Byte, String, String, Timestamp> {

    private static final long serialVersionUID = 1924543570;

    /**
     * Setter for <code>tushare.public_holiday.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tushare.public_holiday.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tushare.public_holiday.ts_date</code>.
     */
    public void setTsDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>tushare.public_holiday.ts_date</code>.
     */
    public Date getTsDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>tushare.public_holiday.is_public_holiday</code>.
     */
    public void setIsPublicHoliday(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>tushare.public_holiday.is_public_holiday</code>.
     */
    public Byte getIsPublicHoliday() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>tushare.public_holiday.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tushare.public_holiday.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tushare.public_holiday.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tushare.public_holiday.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tushare.public_holiday.create_ts</code>.
     */
    public void setCreateTs(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>tushare.public_holiday.create_ts</code>.
     */
    public Timestamp getCreateTs() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Date, Byte, String, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Date, Byte, String, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return PublicHoliday.PUBLIC_HOLIDAY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return PublicHoliday.PUBLIC_HOLIDAY.TS_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field3() {
        return PublicHoliday.PUBLIC_HOLIDAY.IS_PUBLIC_HOLIDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return PublicHoliday.PUBLIC_HOLIDAY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return PublicHoliday.PUBLIC_HOLIDAY.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return PublicHoliday.PUBLIC_HOLIDAY.CREATE_TS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component2() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component3() {
        return getIsPublicHoliday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value3() {
        return getIsPublicHoliday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord value2(Date value) {
        setTsDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord value3(Byte value) {
        setIsPublicHoliday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord value6(Timestamp value) {
        setCreateTs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PublicHolidayRecord values(Long value1, Date value2, Byte value3, String value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PublicHolidayRecord
     */
    public PublicHolidayRecord() {
        super(PublicHoliday.PUBLIC_HOLIDAY);
    }

    /**
     * Create a detached, initialised PublicHolidayRecord
     */
    public PublicHolidayRecord(Long id, Date tsDate, Byte isPublicHoliday, String name, String description, Timestamp createTs) {
        super(PublicHoliday.PUBLIC_HOLIDAY);

        set(0, id);
        set(1, tsDate);
        set(2, isPublicHoliday);
        set(3, name);
        set(4, description);
        set(5, createTs);
    }
}
