/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables.records;


import com.mjiang.email.jooq.domain.tables.SmartWatchRef;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SmartWatchRefRecord extends UpdatableRecordImpl<SmartWatchRefRecord> implements Record7<Long, String, String, String, String, String, String> {

    private static final long serialVersionUID = -742001100;

    /**
     * Setter for <code>tushare.smart_watch_ref.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tushare.smart_watch_ref.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tushare.smart_watch_ref.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tushare.smart_watch_ref.color</code>.
     */
    public void setColor(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.color</code>.
     */
    public String getColor() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tushare.smart_watch_ref.direction</code>.
     */
    public void setDirection(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.direction</code>.
     */
    public String getDirection() {
        return (String) get(4);
    }

    /**
     * Setter for <code>tushare.smart_watch_ref.pair</code>.
     */
    public void setPair(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.pair</code>.
     */
    public String getPair() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tushare.smart_watch_ref.type</code>.
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tushare.smart_watch_ref.type</code>.
     */
    public String getType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return SmartWatchRef.SMART_WATCH_REF.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SmartWatchRef.SMART_WATCH_REF.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SmartWatchRef.SMART_WATCH_REF.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SmartWatchRef.SMART_WATCH_REF.COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return SmartWatchRef.SMART_WATCH_REF.DIRECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return SmartWatchRef.SMART_WATCH_REF.PAIR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return SmartWatchRef.SMART_WATCH_REF.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPair();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDirection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPair();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value2(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value4(String value) {
        setColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value5(String value) {
        setDirection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value6(String value) {
        setPair(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SmartWatchRefRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SmartWatchRefRecord
     */
    public SmartWatchRefRecord() {
        super(SmartWatchRef.SMART_WATCH_REF);
    }

    /**
     * Create a detached, initialised SmartWatchRefRecord
     */
    public SmartWatchRefRecord(Long id, String code, String name, String color, String direction, String pair, String type) {
        super(SmartWatchRef.SMART_WATCH_REF);

        set(0, id);
        set(1, code);
        set(2, name);
        set(3, color);
        set(4, direction);
        set(5, pair);
        set(6, type);
    }
}
