/*
 * This file is generated by jOOQ.
*/
package com.mjiang.email.jooq.domain.tables.records;


import com.mjiang.email.jooq.domain.tables.StockTradeHistoryInfo;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StockTradeHistoryInfoRecord extends UpdatableRecordImpl<StockTradeHistoryInfoRecord> implements Record8<Long, String, Date, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = 1853405793;

    /**
     * Setter for <code>tushare.stock_trade_history_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.stock_code</code>.
     */
    public void setStockCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.stock_code</code>.
     */
    public String getStockCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.ts_date</code>.
     */
    public void setTsDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.ts_date</code>.
     */
    public Date getTsDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.open_price</code>.
     */
    public void setOpenPrice(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.open_price</code>.
     */
    public BigDecimal getOpenPrice() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.close_price</code>.
     */
    public void setClosePrice(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.close_price</code>.
     */
    public BigDecimal getClosePrice() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.high_price</code>.
     */
    public void setHighPrice(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.high_price</code>.
     */
    public BigDecimal getHighPrice() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.low_price</code>.
     */
    public void setLowPrice(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.low_price</code>.
     */
    public BigDecimal getLowPrice() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>tushare.stock_trade_history_info.volume</code>.
     */
    public void setVolume(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>tushare.stock_trade_history_info.volume</code>.
     */
    public BigDecimal getVolume() {
        return (BigDecimal) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Date, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Long, String, Date, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.STOCK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.TS_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.OPEN_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.CLOSE_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.HIGH_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.LOW_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO.VOLUME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getOpenPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getClosePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getHighPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getLowPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getVolume();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getTsDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getOpenPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getClosePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getHighPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getLowPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getVolume();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value2(String value) {
        setStockCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value3(Date value) {
        setTsDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value4(BigDecimal value) {
        setOpenPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value5(BigDecimal value) {
        setClosePrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value6(BigDecimal value) {
        setHighPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value7(BigDecimal value) {
        setLowPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord value8(BigDecimal value) {
        setVolume(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StockTradeHistoryInfoRecord values(Long value1, String value2, Date value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StockTradeHistoryInfoRecord
     */
    public StockTradeHistoryInfoRecord() {
        super(StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO);
    }

    /**
     * Create a detached, initialised StockTradeHistoryInfoRecord
     */
    public StockTradeHistoryInfoRecord(Long id, String stockCode, Date tsDate, BigDecimal openPrice, BigDecimal closePrice, BigDecimal highPrice, BigDecimal lowPrice, BigDecimal volume) {
        super(StockTradeHistoryInfo.STOCK_TRADE_HISTORY_INFO);

        set(0, id);
        set(1, stockCode);
        set(2, tsDate);
        set(3, openPrice);
        set(4, closePrice);
        set(5, highPrice);
        set(6, lowPrice);
        set(7, volume);
    }
}
