/*
 * This file is generated by jOOQ.
*/
package domain;


import domain.tables.BrokerBuyStockInfo;
import domain.tables.BrokerBuySummary;
import domain.tables.DragonTigerStock;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tushare
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tushare.broker_buy_stock_info</code>.
     */
    public static final BrokerBuyStockInfo BROKER_BUY_STOCK_INFO = BrokerBuyStockInfo.BROKER_BUY_STOCK_INFO;

    /**
     * The table <code>tushare.broker_buy_summary</code>.
     */
    public static final BrokerBuySummary BROKER_BUY_SUMMARY = BrokerBuySummary.BROKER_BUY_SUMMARY;

    /**
     * The table <code>tushare.dragon_tiger_stock</code>.
     */
    public static final DragonTigerStock DRAGON_TIGER_STOCK = DragonTigerStock.DRAGON_TIGER_STOCK;
}
